### PR TITLE
Include the version if static and major version if static and non-pre…

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**
…release.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Retriggering Travis.

**Comment by Blackbaud-BobbyEarl** [comment]
Retriggering Travis

**Comment by Blackbaud-BobbyEarl** [comment]
The Travis build is running successfully, but not reporting back unfortunately.

https://travis-ci.org/github/blackbaud/skyux-deploy/builds/666892836

**Comment by Blackbaud-PaulCrowder** [comment]
> The Travis build is running successfully, but not reporting back unfortunately.
> 
> https://travis-ci.org/github/blackbaud/skyux-deploy/builds/666892836

That seems to be happening intermittently lately. I approved the PR.

**Pull request merged**
